export const ORIGINAL_PACKAGE_ID = import.meta.env.VITE_ORIGINAL_PACKAGE_ID;
export const FAUCET_POOL_ID = import.meta.env.VITE_FAUCET_POOL_ID;
export const FAUCET_POOL_MODULE_NAME = import.meta.env
  .VITE_FAUCET_POOL_MODULE_NAME;
export const USDC_LENDING_POOL_ID = import.meta.env.VITE_USDC_LENDING_POOL_ID;
export const USDC_LENDING_POOL_MODULE_NAME = import.meta.env
  .VITE_USDC_LENDING_POOL_MODULE_NAME;

console.log("ORIGINAL_PACKAGE_ID", ORIGINAL_PACKAGE_ID);
console.log("FAUCET_POOL_ID", FAUCET_POOL_ID);
console.log("FAUCET_POOL_MODULE_NAME", FAUCET_POOL_MODULE_NAME);
console.log("USDC_LENDING_POOL_ID", USDC_LENDING_POOL_ID);
console.log("USDC_LENDING_POOL_MODULE_NAME", USDC_LENDING_POOL_MODULE_NAME);
